### ISSUE TITLE
Bulk plant edits

### ISSUE THREAD

**Issue by dvhart** [Thicket-Blender/thicket#14]
Plant selection and edit is currently limited to the active plant (and all identical instances from the same template). The Laubwerk Player for other tools allows for selecting all of the same plant (lbw.gz file) or all plants.

The Thicket edit panel could add a way to identify which plants are affected: e.g. current, all of this plant, all plants and update the panel with the number of instances and templates affected.

This would require the option of "No Change" or similar to avoid changing the plant, model, or season when the intent was to only change some of those.

It may be reasonable to disallow changing the plant for these builk edits.

**Comment by dvhart** [comment]
The batch branch now contains a working prototype. It's a little rough, but much simpler than my initial attempts. Testing and feedback welcome. Minor updates to follow.

**Comment by dvhart** [comment]
@JaWalli and @tdapper heads up if either of you would like to try out and provide feedback on the pre-release batch editing support available in the development pre-release: v0_3_2-batch01:
https://github.com/Thicket-Blender/thicket/releases/tag/v0_3_2-batch01

**Comment by Janwalli** [comment]
@dvhart I had a short look (tested in 2.9) and for me it worked fine. I was able to adjust parameters on two trees at the same time - this comes in very handy!

**Comment by dvhart** [comment]
Thanks @Janwalli , much appreciated. Working on some minor cleanups and we'll get this out in the next release.

**Comment by dvhart** [comment]
Core functionality is now merged to main.
