### ISSUE TITLE
Silence Laubwerk SDK

### ISSUE THREAD

**Issue by dvhart** [Thicket-Blender/thicket#17]
For every call to the Laubwerk SDK get_mesh() function, the SDK prints the following to the console:
```
[debug] Time to create control mesh: 1572ms
[debug] subdiv helper generation time : 0.002604s
[debug] subdiv helper generation time : 0.000803s
```

There is not option to specify the log level of the SDK.

The typical way to address this is via contextlib.redirect_std(out|err). Unfortunately, this doesn't work with the CPython SDK library.

There may not be a way to address this in Thicket, but tracking this here in case someone knows a way around it. Alternatively, we can reach out to Laubwerk to request a loglevel which honors the standard python log levels and pass in the Thicket log level setting to the SDK directly.

**Comment by tdapper** [comment]
I guess that is something we should do on the side of the Laubwerk Python extension. Will look into that!

**Comment by tdapper** [comment]
Just fyi: This has been added to our issue tracker as `LBWPY-148`.

**Comment by tdapper** [comment]
Just an an update: This has been solved internally and will be part of the next update (probably an upcoming version 1.0.42).

**Comment by dvhart** [comment]
Thanks @tdapper will watch for it. Should be a simple patch to incorporate as we moved to loggers for Blender a little while back. Appreciate the heads up!

**Comment by dvhart** [comment]
Due to changes in the Laubwerk API and the lack of current API documentation, I am no longer able to develop or maintain Thicket. Consider trying Laubwerk’s fork of thicket:

https://github.com/Laubwerk/player-for-blender

Thank you for using Thicket, it was a lot of fun to develop.
