### ISSUE TITLE
Separate Laubwerk Plants and Python folders

### ISSUE THREAD

**Issue by dvhart** [Thicket-Blender/thicket#20]
John Payne [reports](https://blenderartists.org/t/request-for-feedback-thicket-free-open-source-laubwerk-plants-add-on-for-blender-2-80/1234777/5) that attempting to change the installation path of a Laubwerk Plant Kit on Windows will install the Plants at the specified destination, but the Python SDK is still installed in "C:\Program Files".

If this is by design, the Thicket Add-on preferences may need to allow specifying the Plants and Python folders individually, rather than assume they both exist under a common Laubwerk installation path.

Need to confirm intent with Laubwerk.

**Comment by dvhart** [comment]
The current Add-on preferences panel provides a single Laubwerk Install Path to configure. To address this issue, the proposed fix would be to include two paths to configure, one for Plants and one for Python.
![thicket-prefs](https://user-images.githubusercontent.com/36253/84605396-ae6a2f80-ae51-11ea-932c-4c0f0b14f9af.png)

**Comment by dvhart** [comment]
The experimental v0_3_1-alpha2 release contains the lbw-paths branch including the updated preferences panel show below:

![Screen Shot 2020-06-14 at 6 59 12 PM](https://user-images.githubusercontent.com/36253/84611341-6b6c8400-ae72-11ea-9de5-6f28b9e23754.png)

**Comment by dvhart** [comment]
Resolved in release v0_3_1.

**Comment by mheljune** [comment]
hi, how do i fix this, theres an error turning on the add on [
![error](https://user-images.githubusercontent.com/73120641/96461830-7176d500-1257-11eb-841b-94ac43682892.png)
](url)

Latest from GitHub (for testers and developers)
Exit Blender
Clone the thicket git repository into the Blender addons folder:
Mac: ~/Library/Blender/2.80/scripts/addons/thicket
Windows: %AppData%\Blender Foundation\Blender\2.80\scripts\addons\thicket
Start Blender

**Comment by dvhart** [comment]
@mheljune moved this to a new issue #28

**Comment by mheljune** [comment]
![error](https://user-images.githubusercontent.com/73120641/96601660-d3514080-1324-11eb-9e7f-a1deffd1326c.png)

i've downloaded the latest laubwerk 1.0.34 and i install it with custom, it seems it doesn't compatible in my pc?

**Comment by dvhart** [comment]
Hi @mheljune , let's please address this in Issue #28 , I'll follow up there. This issue, #20, is unrelated to the problem you are running to.
