### ISSUE TITLE
Add possibility to edit plant materials

### ISSUE THREAD

**Issue by JaWalli** [Thicket-Blender/thicket#22]
As the leaf shaders seemed a bit to reflective for my taste, I tried to edit the materials. But as far as I can see, the plant shaders seem to be hidden from the user.

I would like to see the possibility to dive into materials and edit properties like reflectivity, bump strength or proabably even replace bitmap textures.

**Comment by dvhart** [comment]
Hi @JaWalli , thanks for trying Thicket and reporting this issue.

The Thicket objects visible in the viewport by default are "Collection Instances" (you can't edit them directly). The Materials Nodes are user accessible on the "template" plants in the "Thicket" Collection (not visible in the viewport by default), see the section "Collections and Instancing" in the [README](https://github.com/Thicket-Blender/thicket/blob/master/README.md). Note that unless you selected "Full Geometry" for the Viewport, that there are two models with Materials, one for the viewport and one for rendering, the object name for the latter is indicated with a "(render)" suffix. You can enable the Thicket Collection and Plant Collection of interest below that. Then you'll see the viewport and the render objects in the hierarchy which you can manipulate like any Blender object, including Material Nodes.

During development, we found that different renderers behave differently with the same settings. Cycles, for example, renders bump maps more strongly for the same depth setting compared to Radeon Pro Render. This is something we would be interested in improving. Please let us know the renderer you're using and how you think the materials can be improved for it.

**Comment by JaWalli** [comment]
thanks, I must have missed that and will check out later on. Bump in Cycles indeed seemed to be a bit to strong when close up.

By the way - I am the guy modeling those plants ;-) From time to time I am using Blender, so I am really happy to see a bridge to load the files directly - thanks!

**Comment by dvhart** [comment]
> By the way - I am the guy modeling those plants ;-) From time to time I am using Blender, so I am really happy to see a bridge to load the files directly - thanks!

Awesome, thanks for taking the time to help improve the Blender experience. The plant models are excellent.

**Comment by dvhart** [comment]
@JaWalli you likely have a better idea of the intent behind the various plant material settings in the Laubwerk Plant Kits than I do, so if you think some adjustments could better match the original intent, please let us know. For example, the bump "depth" is set in [lbw_to_bl_mat()](https://github.com/Thicket-Blender/thicket/blob/master/thicket_lbw.py#L211), and was a fairly hand-wavy estimate balancing results from Cycles and Radeon Pro Render. I think it would make sense to optimize for Cycles, and then consider ways to allow for render engine specific settings or Thicket-wide material value tweaks.

**Comment by JaWalli** [comment]
I am not a developer, but I know that materials are receiving an overhaul. It might make sense to wait a bit (I will ask for confirmation) to avoid unnecessary work.

**Comment by JaWalli** [comment]
@dvhart it really might make sense to wait a bit, at last for bigger changes. Especially handling of reflections, but I think also bump might change a bit.
By the way - I am not sure if you are aware, but many leaves on Laubwerk plants make use of different textures and settings for front- and backside. But afaik this only can be seen on high quality materials in other render engines.

Always feel free to contact me, if you have any questions or need help on testing!

**Comment by dvhart** [comment]
@JaWalli thanks for the heads up - and thanks for reminding me about two sided leaves, I have a FIXME in the code, but should open an Issue to address that - and for any other TODOs/FIXMEs lingering in the code still. I'll tag you in material related changes for review and testing - thanks for offering.

As far as this issue goes, did my first response address what you were looking to be able to do? Shall I close this issue, or is there something more we can do here?

**Comment by JaWalli** [comment]
no, material problem was entirely on my side, all fine, issue can be closed - thanks!
