### ISSUE TITLE
Support two sided leaf materials

### ISSUE THREAD

**Issue by dvhart** [Thicket-Blender/thicket#23]
Many Laubwerk plants support two sided leaves with front and back materials. lbw_to_bl_mat() currently assumes one sided. Add logic to detect two sided leaves and investigate how to distinguish the two sides within Blender and apply the backside material.

**Comment by dvhart** [comment]
This should be doable with the mix and geometry::backface material nodes (shader) as shown here:
https://www.blendernation.com/2019/03/13/double-sided-shader-tutorial-for-blender-2-8/

<img width="2066" alt="Screen Shot 2020-07-07 at 1 22 32 PM" src="https://user-images.githubusercontent.com/36253/86838474-11b43f80-c055-11ea-97e7-8e5e2f2638cb.png">

**Comment by dvhart** [comment]
@JaWalli would you be willing to test this update adding support for two sided materials?
[thicket-two-sided.zip](https://github.com/Thicket-Blender/thicket/files/4894102/thicket-two-sided.zip)

I confirmed two sided leaves on the Middle Aged Acer Palmatum Fall model.

I am particularly interested in knowing if the two textures are applied to the correct sides of the leaves (e.g. is the top always on the top).

**Comment by JaWalli** [comment]
@dvhart I had a look at several plant models, on all the result was flipped. My first intention was to switch the order of the Mix node, but actually it seems to be the mesh normals pointing into the wrong direction - please see attached image.
The normals on the leaves point downwards and on the trunk inwards. I think you just need to flip the normals!
![catalpa_normals](https://user-images.githubusercontent.com/67624378/87006427-f23a2580-c1c0-11ea-833a-e723c4c61f37.jpg)

**Comment by dvhart** [comment]
Thanks for catching that @JaWalli . Simple fix attached:
[thicket-two-sided-v2.zip](https://github.com/Thicket-Blender/thicket/files/4901119/thicket-two-sided-v2.zip)

**Comment by dvhart** [comment]
Thanks @JaWalli , I've simplified the geometry creation code and was able to correct the normals without having to explicitly flip them (by removing some manual point manipulation in the import code and replacing it with a matrix transform). I believe this should now work as expected. 
[thicket-two-sided_v3.zip](https://github.com/Thicket-Blender/thicket/files/4901566/thicket-two-sided_v3.zip)

**Comment by JaWalli** [comment]
v3 seems to work very nice. Tested on a few plants and front back side now works like intended. Good job!

**Comment by dvhart** [comment]
Merged with PR #24
