### ISSUE TITLE
thicket throws python errror when trying to add plant 

### ISSUE THREAD

**Issue by tnsor** [Thicket-Blender/thicket#26]
Tested in 2.80, 2.82 and 2.91
I always get the following error
```

INFO: thicket: Importing "Abies koreana"
[debug] Time to create control mesh: 60ms
[debug] subdiv helper generation time : 0.121s
[debug] subdiv helper generation time : 0.129s
[debug] subdiv helper generation time : 0.127s
[debug] subdiv helper generation time : 0.024s
Traceback (most recent call last):
  File "C:\Users\mnu\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\thicket-0_3_2\__init__.py", line 661, in execute
    thicket_ui_obj = tp.import_lbw()
  File "C:\Users\mnu\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\thicket-0_3_2\__init__.py", line 380, in import_lbw
    return thicket_lbw.import_lbw(filepath, self.model, self.viewport_lod, self.render_lod, mesh_args)
  File "C:\Users\mnu\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\thicket-0_3_2\thicket_lbw.py", line 284, in import_lbw
    render_lod == 'PROXY')
  File "C:\Users\mnu\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\thicket-0_3_2\thicket_lbw.py", line 100, in lbw_to_bl_obj
    mat = lbw_to_bl_mat(lbw_plant, mat_id, mat_name, qualifier, proxy_color)
  File "C:\Users\mnu\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\thicket-0_3_2\thicket_lbw.py", line 134, in lbw_to_bl_mat
    mat.diffuse_color = proxy_color or lbw_mat.get_front().diffuse_color + (1.0,)
AttributeError: 'Side' object has no attribute 'diffuse_color'

location: <unknown location>:-1
```

Thanx, mnu

**Comment by dvhart** [comment]
Thanks for reporting this issue @tnsor . This appears to be an incompatible version of the Laubwerk Python Binding. Which version of the Laubwerk Python Binding do you have installed? This is displayed in the Blender Preferences -> Add-ons -> Thicket -> Laubwerk Installation.

**Comment by dvhart** [comment]
I checked the Laubwerk Downloads and version 1.0.34 was recently released and it introduces this API change since 1.0.33. I am able to reproduce the error reported. Following up with Laubwerk on how to proceed.

**Comment by tdapper** [comment]
This was our mistake. We did introduce an API breaking change with something that, by version number, should only be a revision. I'm updating the documentation as we speak and pledge to be more careful about versioning and communication in the future!

**Comment by dvhart** [comment]
Thanks @tdapper - I'll take a closer look at what it will take to support both 1.0.33 and 1.0.34 concurrently, which I think we should be able to manage. Thanks for following up here on the ticket, Laubwerks' support and transparency has made this project possible +1.

**Comment by dvhart** [comment]
From @tdapper in #27 : Some material properties have been renamed (e.g. diffuse_color to base_color and a bunch have been added (e.g. specular_roughness_texture or sheen).

Thanks, this is the information we need to address. @tnsor I'll follow up here with an update soon.

**Comment by tdapper** [comment]
I'll update the downloads with the proper documentation later, but here it is for you to work with, @dvhart:
[help.zip](https://github.com/Thicket-Blender/thicket/files/5387113/help.zip)

**Comment by tnsor** [comment]
cool, thanx, that was fast. I'm using the old python bindings in the meantime!

**Comment by dvhart** [comment]
@tnsor I've posted a new release (v0_3_3) with support for Laubwerk 1.0.34 materials. See the releases page for Thicket v0_3_3: https://github.com/Thicket-Blender/thicket/releases/tag/v0_3_3

Please let me know if this works for you. Thanks!

**Comment by dvhart** [comment]
Considering this resolved. Please let us know by commenting here if this does not address the issue for you.

**Comment by tdapper** [comment]
I tried it today and it worked just fine for me.
