### ISSUE TITLE
Index of refraction should be 1.33

### ISSUE THREAD

**Issue by tdapper** [Thicket-Blender/thicket#30]
We at Laubwerk currently do not explicitly store the index of refraction, but implicitly assume the index of refraction for all Laubwerk materials to be 1.33. That should be reflected, until the index of refraction is explicitly stored, for materials compatibility between different host applications.

**Comment by dvhart** [comment]
Thanks for the feedback - easily addressed. Patch submitted and queued for the next release.

**Comment by dvhart** [comment]
Merged to main.
