### ISSUE TITLE
Translucency seems to be missing

### ISSUE THREAD

**Issue by tdapper** [Thicket-Blender/thicket#35]
It appears that translucency is missing from materials. I haven't been able to find it on any model I tested so far.

Adding translucency does appear to be a bit of a pita, though: https://blender.stackexchange.com/questions/93686/transluscent-leaf-using-principled-shader

**Comment by dvhart** [comment]
Hrm, interesting, looks like I conflated "translucency" with "transmittance", and we want both.

**Comment by tdapper** [comment]
No, we do not want both. Transmission models transparency, which Laubwerk materials do not have.

We only want to model translucency, which is a special case of subsurface scattering for thin sheet objects.

**Comment by dvhart** [comment]
OK, thanks for clarifying terms - I hadn't realized I had a knowledge gap there. Looked into this some more, and now think I understand the difference between transparent (transmission) and translucent. In this image, I show what Thicket does today with transmission (which I now understand to be wrong) and a manually tweaked material node graph using a Translucent BSDF and a Mix Shader to produce "translucent" leaves. I believe the result is headed in the right direction.

![Screen Shot 2020-10-25 at 11 43 48 AM](https://user-images.githubusercontent.com/36253/97116042-e31bac80-16b7-11eb-9579-d56642564d84.png)

Please confirm "laubwerk.material.subsurface_color" should be used for the Translucent BSDF color? ("subsurface_color" is not included in the 1.0.34 documentation as of this morning).

Note: I am handling this separately from the two-sided issue which will further modify how these node graphs come together.

**Comment by tdapper** [comment]
Thanks for the improvement. Looking good. There appears to be some depth to the problem, that the link I sent you did not fully reflect. Please check https://devtalk.blender.org/t/diffuse-translucency-way-too-difficult-to-set-up-in-cycles/807. I can take the lead here and figure out what the setup should really look like. It may just take a little.

As for `subsurface_color` (and `subsurface_color_texture`): Yes, you understand correctly and I added the missing documentation so it's going to be included in the next version.

As for the two sided issue (https://github.com/Thicket-Blender/thicket/issues/32), you may want to do that one first, as it's apparently much simpler. :-o

**Comment by dvhart** [comment]
@tdapper I have provided a partial solution when implements the node network above. It isn't complete, but it's at least an improvement of using Transmission and we can build on it from there. Note this is currently only in the "materials" topic branch and has not yet been proposed to merge to master (but likely will soon).

If you would like to take the lead on suggesting a node network which reflects the intent of the Laubwerk material properties, that would be excellent. I will leave this issue open to continue to discuss and track progress.

**Comment by dvhart** [comment]
Due to changes in the Laubwerk API and the lack of current API documentation, I am no longer able to develop or maintain Thicket. Consider trying Laubwerk’s fork of thicket:

https://github.com/Laubwerk/player-for-blender

Thank you for using Thicket, it was a lot of fun to develop.
