### ISSUE TITLE
Re-use texture input nodes

### ISSUE THREAD

**Issue by tdapper** [Thicket-Blender/thicket#39]
Quoting myself from https://github.com/Thicket-Blender/thicket/issues/32:

> One possible optimization (not sure if it has any performance implications, but it may simplify/clarify the material graph): Perhaps keep a list of texture input nodes around and just re-use a node when a texture is used multiple times (with the same color space setting). In the example above, e.g. the input node for the front BSDF color could be re-used as input to the Mix BSDF node.

**Comment by dvhart** [comment]
Due to changes in the Laubwerk API and the lack of current API documentation, I am no longer able to develop or maintain Thicket. Consider trying Laubwerk’s fork of thicket:

https://github.com/Laubwerk/player-for-blender

Thank you for using Thicket, it was a lot of fun to develop.
