### ISSUE TITLE
Update for Blender 3.0 API Changes (bpy.utils.user_resource)

### ISSUE THREAD

**Issue by Mi-Pe** [Thicket-Blender/thicket#52]
Hello,
Thicket works fine in Blender 2.92, but since version 2.93 they are using Python 3.9 instead of 3.7, and that breaks some addons, including Thicket.
I tested it on Blender 3.0.0 alpha. It can be installed, but cannot be enabled (ticked) in addon preferences. It throws such an error:

"
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\E-Cycles_X_Pro_3.0_a_20211008_win\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\thicket-0_4_0\__init__.py", line 70, in <module>
    log_path = Path(bpy.utils.user_resource('SCRIPTS', "addons", True)) / __name__ / "thicket.log"
TypeError: user_resource() takes 1 positional argument but 3 were given
"

Is there a chance for an update for newest Blender versions?

Best regards

**Comment by dvhart** [comment]
Hi @Mi-Pe , thank you for reporting and providing the traceback, this will help speed up time to a fix. This looks like it should be a fairly straight forward fix. I should have to dig into it no later than this weekend. If someone else wants to try their hand at a fix before then, the help would be welcome.

**Comment by Mi-Pe** [comment]
Great, thank you!
I will be happy to see the update :)

**Comment by dvhart** [comment]
Resolved in v0_4_1
