### ISSUE TITLE
Python extension not accepted (Laubwerk 1.0.39 on MacOS only)

### ISSUE THREAD

**Issue by steckhan** [Thicket-Blender/thicket#53]
**Describe the bug**
Somehow the path to the Python extension in Blenders Plugin Settings is not accepted.

**To Reproduce**
1. Go to Blender and 
2. Click on path for Python extensions
4. See error, path appears red, unfortunately plugin is still disabled

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version [10.15.2]
 - Blender Version [2.81a]

**Comment by dvhart** [comment]
This issue has been resolved with updated releases from Laubwerk.
