### ISSUE TITLE
Not found module thicket-blender_3

### ISSUE THREAD

**Issue by c1symeon** [Thicket-Blender/thicket#55]
Hi and thanks for developing this.
I installed the main branch version in Blender 2.91, all fine.
Then I tried  the branch for version Blender 3.0.  After installing from the .zip, when trying to activate I would get an error : 
"not able to find module thicket-blender_3"
Looking in the ..AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons I found a folder named "thicket-blender_3.0" ,  I renamed that "thicket-blender_3", restarted Blender and it worked.

**Comment by dvhart** [comment]
Thanks for reporting this. Which release image did you download and install? Did you install through Preferences->Add-ons->Install... ?

When installing 4.1.0-rc0 for Blender 3.0.1 (on Mac OS), it installs in scripts/addons/thicket-0_4_1_rc0.

The specific release image I tested with is marked a development release (I need to go back and create the official release - oops):
https://github.com/Thicket-Blender/thicket/archive/refs/tags/v0_4_1_rc0.zip

**Comment by c1symeon** [comment]
![image](https://user-images.githubusercontent.com/61176887/156152741-3e139ca7-be4d-48b5-93e5-7f54e91a42f6.png)
Above is a snippet of what I downloaded (from the branch), it appeared to be the latest and about Blender 3.0.

Installed and activated in Blender 3.0, under Preferences, it is shown as being version 0.4.1

**Comment by dvhart** [comment]
@c1symeon Ah, I see. So the branch is the same code, the difference is just in how it's packaged which leads to a difference in the directory naming. The branches are intended for development. For Pleaase see the Install section in the README.md (displayed on the project main page: https://github.com/Thicket-Blender/thicket) and in there you'll find a pointer to the "Releases Tab" (also visible in the right hand column). You want to download the "thicket-v0_4_1_rc0" pre-release zip file, and install this zip file through the preferences->Add-ons->install... procedure. I'll also get a final release published for 0.4.1 (but it will be the same exact code - no need to wait for that). Let me know if this addresses the issue for you and we'll close this out.

**Comment by c1symeon** [comment]
You can close it out already.  I have changed the directory and it worked even before I wrote about this (it was working when I filed the issue) and if that's the only difference with the release I'll wait for a more significant update.  Thanks!

For me it would be interesting if I can package a tree I define in the way Laubwerk does.  But this is proprietary info?  they distribute the app only as I a base for selling the libraries, right?  and your work is an open source bridge for Blender?

**Comment by dvhart** [comment]
That's right. Laubwerk sells their tree packs, and make players/plugins and the Python software development kit (sdk) available to use those proprietary models. Thicket makes use of the Python SDK, but has no visibility into the models beyond what functionality exposed by their SDK.
